-- Career Activity Tracker — D1 schema
-- 8 tables, one per original spreadsheet tab.
-- Every table carries the same audit columns so accountability
-- (who created/last touched a row, and when) is automatic.

CREATE TABLE IF NOT EXISTS networking (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  full_name TEXT,
  title_role TEXT,
  company_org TEXT,
  industry TEXT,
  channel TEXT,
  contact_info TEXT,
  connection_source TEXT,
  first_outreach_date TEXT,
  last_contact_date TEXT,
  follow_up_date TEXT,
  status TEXT,
  purpose TEXT,
  relationship_strength INTEGER,
  owner TEXT,
  linked_opportunity TEXT,
  priority TEXT,
  notes TEXT,
  created_by TEXT,
  created_at TEXT,
  updated_by TEXT,
  updated_at TEXT
);

CREATE TABLE IF NOT EXISTS job_apps (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  company TEXT,
  role_title TEXT,
  location TEXT,
  job_type TEXT,
  source TEXT,
  job_url TEXT,
  date_applied TEXT,
  application_deadline TEXT,
  status TEXT,
  salary_range TEXT,
  contact_recruiter TEXT,
  resume_version TEXT,
  cover_letter TEXT,
  interview_date TEXT,
  interview_notes TEXT,
  follow_up_date TEXT,
  owner TEXT,
  notes TEXT,
  created_by TEXT,
  created_at TEXT,
  updated_by TEXT,
  updated_at TEXT
);

CREATE TABLE IF NOT EXISTS grad_school (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  university TEXT,
  program_degree TEXT,
  country TEXT,
  degree_level TEXT,
  application_deadline TEXT,
  date_submitted TEXT,
  status TEXT,
  tuition_funding TEXT,
  scholarship_available TEXT,
  gre_gmat_required TEXT,
  sop_status TEXT,
  lor_status TEXT,
  transcript_status TEXT,
  interview_date TEXT,
  decision_date TEXT,
  owner TEXT,
  notes TEXT,
  created_by TEXT,
  created_at TEXT,
  updated_by TEXT,
  updated_at TEXT
);

CREATE TABLE IF NOT EXISTS grants (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  program_name TEXT,
  organisation_funder TEXT,
  type TEXT,
  amount_value TEXT,
  eligibility_notes TEXT,
  application_deadline TEXT,
  date_applied TEXT,
  status TEXT,
  documents_required TEXT,
  lors_needed TEXT,
  essay_status TEXT,
  decision_date TEXT,
  owner TEXT,
  link_url TEXT,
  notes TEXT,
  created_by TEXT,
  created_at TEXT,
  updated_by TEXT,
  updated_at TEXT
);

CREATE TABLE IF NOT EXISTS articles (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  title TEXT,
  platform TEXT,
  category_topic TEXT,
  format TEXT,
  target_audience TEXT,
  target_word_count INTEGER,
  status TEXT,
  idea_date TEXT,
  draft_due_date TEXT,
  submit_publish_date TEXT,
  date_published TEXT,
  link_url TEXT,
  seo_keywords TEXT,
  owner TEXT,
  co_author TEXT,
  performance_notes TEXT,
  notes TEXT,
  created_by TEXT,
  created_at TEXT,
  updated_by TEXT,
  updated_at TEXT
);

CREATE TABLE IF NOT EXISTS linkedin_posts (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  post_topic TEXT,
  post_type TEXT,
  content_pillar TEXT,
  target_audience TEXT,
  draft_caption TEXT,
  status TEXT,
  planned_post_date TEXT,
  date_posted TEXT,
  post_url TEXT,
  owner TEXT,
  hashtags TEXT,
  impressions INTEGER,
  likes INTEGER,
  comments INTEGER,
  notes TEXT,
  created_by TEXT,
  created_at TEXT,
  updated_by TEXT,
  updated_at TEXT
);

CREATE TABLE IF NOT EXISTS courses_certs (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT,
  type TEXT,
  platform_provider TEXT,
  certification_body TEXT,
  stage_module TEXT,
  total_modules REAL,
  modules_completed REAL,
  percent_complete REAL,
  current_module TEXT,
  status TEXT,
  start_date TEXT,
  target_completion TEXT,
  date_completed TEXT,
  study_hours REAL,
  exam_date TEXT,
  exam_result TEXT,
  owner TEXT,
  link_url TEXT,
  notes TEXT,
  created_by TEXT,
  created_at TEXT,
  updated_by TEXT,
  updated_at TEXT
);

CREATE TABLE IF NOT EXISTS books_papers (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  title TEXT,
  authors TEXT,
  type TEXT,
  genre_field TEXT,
  publisher_journal TEXT,
  year INTEGER,
  source_link TEXT,
  format TEXT,
  status TEXT,
  start_date TEXT,
  date_finished TEXT,
  current_chapter TEXT,
  total_chapters TEXT,
  key_takeaways TEXT,
  rating REAL,
  owner TEXT,
  notes TEXT,
  created_by TEXT,
  created_at TEXT,
  updated_by TEXT,
  updated_at TEXT
);
