-- Seed data imported from Career_Development_Activity_Tracker.xlsx on 2026-06-25

INSERT INTO networking (full_name, title_role, company_org, industry, channel, contact_info, connection_source, first_outreach_date, last_contact_date, follow_up_date, status, purpose, relationship_strength, owner, linked_opportunity, priority, notes, created_by, created_at, updated_by, updated_at) VALUES ('Alex Johnson', 'Head of Product', 'TechCorp Lagos', 'Tech', 'LinkedIn', 'linkedin.com/in/alexj', 'DevFest Conference', '2025-01-10', '2025-01-15', '2025-02-01', 'Replied', 'Job Referral', 3, 'Tomiwa', 'Software PM @ TechCorp', '⭐⭐⭐', 'Very responsive. Follow up re: open role.', 'Tomiwa', '2026-06-25T00:00:00Z', 'Tomiwa', '2026-06-25T00:00:00Z');
INSERT INTO job_apps (company, role_title, location, job_type, source, job_url, date_applied, application_deadline, status, salary_range, contact_recruiter, resume_version, cover_letter, interview_date, interview_notes, follow_up_date, owner, notes, created_by, created_at, updated_by, updated_at) VALUES ('Youth for Responsible AI', NULL, 'Remote', 'Internship', 'LinkedIn', 'https://youthforresponsibleai.com/', '2026-06-08', '2026-06-25', 'Applied', 'No salary', NULL, NULL, 'No', NULL, NULL, NULL, 'Ebunoluwa', NULL, 'Ebunoluwa', '2026-06-25T00:00:00Z', 'Ebunoluwa', '2026-06-25T00:00:00Z');
INSERT INTO job_apps (company, role_title, location, job_type, source, job_url, date_applied, application_deadline, status, salary_range, contact_recruiter, resume_version, cover_letter, interview_date, interview_notes, follow_up_date, owner, notes, created_by, created_at, updated_by, updated_at) VALUES ('PagaTech', 'Learning & Development Analyst', 'Yaba, Lagos (Hybrid)', 'Full-Time', 'JobMag', 'https://paga.bamboohr.com/careers/426', '2026-06-08', NULL, 'Applied', '400000-450000', NULL, 'Akintomiwa Paul Awoyomi CV.pdf', 'No', NULL, NULL, NULL, 'Tomiwa', 'Paga has spent fifteen years pioneering payments infrastructure, and the PayPal collaboration marks the start of a new chapter in that story. I want to be part of what comes next — and I think L&D is one of the most direct ways to contribute to it.

Scaling scope and ambition requires people who are growing alongside the organisation. That''s what well-designed learning and development makes possible. My experience building training systems at Nestlé and Telinno — in environments where those systems didn''t previously exist — is exactly the kind of work I want to do more of, at a company with Paga''s trajectory.

I''m interested in pioneering, and Paga is a place where that instinct has a home.', 'Tomiwa', '2026-06-25T00:00:00Z', 'Tomiwa', '2026-06-25T00:00:00Z');
INSERT INTO job_apps (company, role_title, location, job_type, source, job_url, date_applied, application_deadline, status, salary_range, contact_recruiter, resume_version, cover_letter, interview_date, interview_notes, follow_up_date, owner, notes, created_by, created_at, updated_by, updated_at) VALUES ('FairMoney', 'People & Culture Specialist', 'Lagos, Nigeria', 'Full-Time', 'LinkedIn', 'https://apply.workable.com/fairmoney/j/D28981B155/apply/?success', '2026-06-09', NULL, 'Applied', NULL, NULL, 'Akintomiwa_Awoyomi_CV_FM', 'Yes', NULL, NULL, NULL, 'Tomiwa', 'Dear Hiring Team,
FairMoney has built something rare — a mobile banking platform that genuinely meets emerging market users where they are. From microcredit to a full suite of accounts, cards, and POS solutions, the trajectory is clear: a company that keeps expanding scope without losing focus. That''s the kind of organisation I want to grow with.
I''m applying for the People & Culture Specialist role because it maps directly onto what I''ve spent the last two years building. At Telinno Consulting, I manage the full lifecycle of outsourced staff on a major key account — supply, training, certification, grievance resolution, and compliance — while also designing the HR governance programme that brought vendor personnel in line with organisational standards. Before that, I built hiring frameworks from scratch at Realhouse Communications and managed 500+ employee records, benefits administration, and compliance documentation at Nestlé.
Beyond the functional skills, I bring a systems mindset. The capacity-building programme I built at Nestlé still runs without me. The governance framework at Telinno outlasted my initial brief. I build things that scale — and I''d like to bring that to FairMoney''s people operations.
I''d welcome the opportunity to speak with your team.', 'Tomiwa', '2026-06-25T00:00:00Z', 'Tomiwa', '2026-06-25T00:00:00Z');
INSERT INTO grad_school (university, program_degree, country, degree_level, application_deadline, date_submitted, status, tuition_funding, scholarship_available, gre_gmat_required, sop_status, lor_status, transcript_status, interview_date, decision_date, owner, notes, created_by, created_at, updated_by, updated_at) VALUES ('LSE', 'MSc Development Economics', 'UK', 'MSc', '2025-01-15', '2025-01-12', 'Submitted', '£28,000/yr', 'Partial', 'No', 'Submitted', '3/3', 'Sent', NULL, '2025-03-01', 'Ebunoluwa', 'Strong programme. Awaiting decision.', 'Ebunoluwa', '2026-06-25T00:00:00Z', 'Ebunoluwa', '2026-06-25T00:00:00Z');
INSERT INTO grad_school (university, program_degree, country, degree_level, application_deadline, date_submitted, status, tuition_funding, scholarship_available, gre_gmat_required, sop_status, lor_status, transcript_status, interview_date, decision_date, owner, notes, created_by, created_at, updated_by, updated_at) VALUES ('University of Cape Town', 'MBA', 'South Africa', 'MBA', '2025-02-01', NULL, 'Preparing', 'R95,000/yr', 'Merit Grant', 'No', 'Drafting', '1/3', 'Not Sent', NULL, '2025-04-15', 'Ebunoluwa', '2 more LORs needed by Jan 25.', 'Ebunoluwa', '2026-06-25T00:00:00Z', 'Ebunoluwa', '2026-06-25T00:00:00Z');
INSERT INTO grad_school (university, program_degree, country, degree_level, application_deadline, date_submitted, status, tuition_funding, scholarship_available, gre_gmat_required, sop_status, lor_status, transcript_status, interview_date, decision_date, owner, notes, created_by, created_at, updated_by, updated_at) VALUES ('Columbia SIPA', 'MPA — Technology Policy', 'USA', 'MPA', '2025-01-05', '2025-01-03', 'Interview', '$70,000/yr', 'Need-Based', 'No', 'Submitted', '3/3', 'Sent', '2025-01-28', '2025-03-15', 'Tomiwa', 'Interview scheduled! Prep hard.', 'Tomiwa', '2026-06-25T00:00:00Z', 'Tomiwa', '2026-06-25T00:00:00Z');
INSERT INTO grants (program_name, organisation_funder, type, amount_value, eligibility_notes, application_deadline, date_applied, status, documents_required, lors_needed, essay_status, decision_date, owner, link_url, notes, created_by, created_at, updated_by, updated_at) VALUES ('Tony Elumelu Foundation Grant', 'TEF', 'Grant', '$5,000 USD', 'African entrepreneur, early-stage business', '2025-01-31', NULL, 'Preparing', 'Business Plan, Pitch Deck', 'No', 'Drafting', '2025-06-01', 'Both', 'tefoundation.org', 'Top priority. Business plan 70% done.', 'Tomiwa', '2026-06-25T00:00:00Z', 'Tomiwa', '2026-06-25T00:00:00Z');
INSERT INTO grants (program_name, organisation_funder, type, amount_value, eligibility_notes, application_deadline, date_applied, status, documents_required, lors_needed, essay_status, decision_date, owner, link_url, notes, created_by, created_at, updated_by, updated_at) VALUES ('MasterCard Foundation Scholars', 'MCF', 'Fellowship', 'Full Funding', 'African student, financial need', '2025-02-15', NULL, 'Researching', 'Transcript, LOR x2, Essays', 'Yes — 2', 'Not Started', '2025-05-15', 'Ebunoluwa', 'mastercardfdn.org', 'Reach opportunity. Start essays ASAP.', 'Ebunoluwa', '2026-06-25T00:00:00Z', 'Ebunoluwa', '2026-06-25T00:00:00Z');
INSERT INTO grants (program_name, organisation_funder, type, amount_value, eligibility_notes, application_deadline, date_applied, status, documents_required, lors_needed, essay_status, decision_date, owner, link_url, notes, created_by, created_at, updated_by, updated_at) VALUES ('Google for Startups Africa', 'Google', 'Accelerator', '$350k equity-free', 'Tech startup, Africa-based', '2025-03-01', NULL, 'Researching', 'Deck, Financials', 'No', 'Not Started', '2025-06-30', 'Tomiwa', 'startup.google.com', 'New cohort opens Feb 2025.', 'Tomiwa', '2026-06-25T00:00:00Z', 'Tomiwa', '2026-06-25T00:00:00Z');
INSERT INTO articles (title, platform, category_topic, format, target_audience, target_word_count, status, idea_date, draft_due_date, submit_publish_date, date_published, link_url, seo_keywords, owner, co_author, performance_notes, notes, created_by, created_at, updated_by, updated_at) VALUES ('Why African Startups Should Think Global From Day One', 'Medium', 'Entrepreneurship', 'Essay', 'Founders & Investors', 1800, 'Drafting', '2025-01-05', '2025-01-20', '2025-02-01', NULL, NULL, 'Africa, startups, global scaling', 'Tomiwa', 'No', NULL, 'First draft at 60%. Strong hook needed.', 'Tomiwa', '2026-06-25T00:00:00Z', 'Tomiwa', '2026-06-25T00:00:00Z');
INSERT INTO articles (title, platform, category_topic, format, target_audience, target_word_count, status, idea_date, draft_due_date, submit_publish_date, date_published, link_url, seo_keywords, owner, co_author, performance_notes, notes, created_by, created_at, updated_by, updated_at) VALUES ('My Journey Applying to Grad School in 2025', 'Substack', 'Personal / Career', 'Blog Post', 'Students & Young Professionals', 2200, 'Outline', '2025-01-08', '2025-01-25', '2025-02-10', NULL, NULL, 'grad school, applications, Africa', 'Ebunoluwa', 'No', NULL, 'Outline done. Start drafting this week.', 'Ebunoluwa', '2026-06-25T00:00:00Z', 'Ebunoluwa', '2026-06-25T00:00:00Z');
INSERT INTO articles (title, platform, category_topic, format, target_audience, target_word_count, status, idea_date, draft_due_date, submit_publish_date, date_published, link_url, seo_keywords, owner, co_author, performance_notes, notes, created_by, created_at, updated_by, updated_at) VALUES ('The Gender Gap in Tech Leadership: Data & Solutions', 'LinkedIn Articles', 'DEI / Tech', 'Research Piece', 'HR & Tech Leaders', 2500, 'Idea', '2025-01-15', '2025-02-10', '2025-02-28', NULL, NULL, 'gender, tech leadership, diversity', 'Both', 'Yes', NULL, 'Collaborative piece. Gather data first.', 'Tomiwa', '2026-06-25T00:00:00Z', 'Tomiwa', '2026-06-25T00:00:00Z');
INSERT INTO linkedin_posts (post_topic, post_type, content_pillar, target_audience, draft_caption, status, planned_post_date, date_posted, post_url, owner, hashtags, impressions, likes, comments, notes, created_by, created_at, updated_by, updated_at) VALUES ('Most people apply to jobs wrong. Here''s what I learned after 50+ applications…', 'Text Post', 'Career & Job Search', 'Job Seekers & HR', 'Draft in notes', 'Draft Ready', '2025-01-22', NULL, NULL, 'Tomiwa', '#jobsearch #career #Nigeria', NULL, NULL, NULL, 'Strong hook. Needs 3 concrete tips + CTA.', 'Tomiwa', '2026-06-25T00:00:00Z', 'Tomiwa', '2026-06-25T00:00:00Z');
INSERT INTO linkedin_posts (post_topic, post_type, content_pillar, target_audience, draft_caption, status, planned_post_date, date_posted, post_url, owner, hashtags, impressions, likes, comments, notes, created_by, created_at, updated_by, updated_at) VALUES ('I just submitted my grad school applications. Here''s the honest truth nobody tells you…', 'Text Post', 'Education & Personal Growth', 'Students & Young Professionals', 'Draft in Notion', 'Drafting', '2025-01-28', NULL, NULL, 'Ebunoluwa', '#gradschool #education #Africa', NULL, NULL, NULL, 'Vulnerable storytelling angle. Very shareable.', 'Ebunoluwa', '2026-06-25T00:00:00Z', 'Ebunoluwa', '2026-06-25T00:00:00Z');
INSERT INTO linkedin_posts (post_topic, post_type, content_pillar, target_audience, draft_caption, status, planned_post_date, date_posted, post_url, owner, hashtags, impressions, likes, comments, notes, created_by, created_at, updated_by, updated_at) VALUES ('5 African grants you can apply to RIGHT NOW (most people don''t know these exist)', 'Carousel', 'Opportunities & Funding', 'Students & Early Professionals', 'Slide outline ready', 'Draft Ready', '2025-02-02', NULL, NULL, 'Both', '#grants #Africa #opportunities', NULL, NULL, NULL, 'Carousel format — 6 slides. Design needed.', 'Tomiwa', '2026-06-25T00:00:00Z', 'Tomiwa', '2026-06-25T00:00:00Z');
INSERT INTO courses_certs (name, type, platform_provider, certification_body, stage_module, total_modules, modules_completed, percent_complete, current_module, status, start_date, target_completion, date_completed, study_hours, exam_date, exam_result, owner, link_url, notes, created_by, created_at, updated_by, updated_at) VALUES ('Learn Politics', 'Course', 'Learn Politics Platform', '—', '—', 10, 1, 0.1, 'Module 1 — Intro to Political Systems', 'In Progress', '2025-01-12', '2025-03-15', NULL, 2, NULL, NULL, 'Ebunoluwa', 'learnpolitics.com', 'Starting with political theory fundamentals.', 'Ebunoluwa', '2026-06-25T00:00:00Z', 'Ebunoluwa', '2026-06-25T00:00:00Z');
INSERT INTO courses_certs (name, type, platform_provider, certification_body, stage_module, total_modules, modules_completed, percent_complete, current_module, status, start_date, target_completion, date_completed, study_hours, exam_date, exam_result, owner, link_url, notes, created_by, created_at, updated_by, updated_at) VALUES ('CIPM', 'Cert Stage', 'CIPM Nigeria', 'CIPM Nigeria', 'Part 1 — Foundation', 1, 1, 1, 'Completed', 'Completed', '2024-06-01', '2024-12-01', '2024-11-20', 60, '2024-11-20', 'Pass', 'Tomiwa', 'cipm.ng', 'Foundation stage cleared.', 'Tomiwa', '2026-06-25T00:00:00Z', 'Tomiwa', '2026-06-25T00:00:00Z');
INSERT INTO books_papers (title, authors, type, genre_field, publisher_journal, year, source_link, format, status, start_date, date_finished, current_chapter, total_chapters, key_takeaways, rating, owner, notes, created_by, created_at, updated_by, updated_at) VALUES ('Thinking, Fast and Slow', 'Daniel Kahneman', 'Book', 'Psychology / Behavioural Economics', 'Farrar, Straus and Giroux', 2011, NULL, 'Physical', 'Reading', '2025-01-05', NULL, 'Chapter 14', '38 chapters', 'System 1 vs System 2 thinking. Biases are predictable and systematic.', 4, 'Tomiwa', 'Excellent read. Taking notes per chapter.', 'Tomiwa', '2026-06-25T00:00:00Z', 'Tomiwa', '2026-06-25T00:00:00Z');
INSERT INTO books_papers (title, authors, type, genre_field, publisher_journal, year, source_link, format, status, start_date, date_finished, current_chapter, total_chapters, key_takeaways, rating, owner, notes, created_by, created_at, updated_by, updated_at) VALUES ('The Wretched of the Earth', 'Frantz Fanon', 'Book', 'Politics / Post-colonialism', 'Grove Press', 1961, NULL, 'eBook', 'Want to Read', NULL, NULL, NULL, NULL, 'Anti-colonial classic. On decolonisation and national consciousness.', NULL, 'Ebunoluwa', 'Recommended in Learn Politics course.', 'Ebunoluwa', '2026-06-25T00:00:00Z', 'Ebunoluwa', '2026-06-25T00:00:00Z');
INSERT INTO books_papers (title, authors, type, genre_field, publisher_journal, year, source_link, format, status, start_date, date_finished, current_chapter, total_chapters, key_takeaways, rating, owner, notes, created_by, created_at, updated_by, updated_at) VALUES ('Artificial Intelligence and the Future of Work in Africa', 'Various Authors', 'Academic Paper', 'AI / Labour Economics', 'African Development Bank Journal', 2023, 'afdb.org/research/…', 'PDF', 'Finished', '2025-01-08', '2025-01-10', NULL, '22 pages', 'AI adoption in Africa concentrated in fintech & agriculture. Skills gap is the core risk.', 5, 'Both', 'Cite in TEF grant application.', 'Tomiwa', '2026-06-25T00:00:00Z', 'Tomiwa', '2026-06-25T00:00:00Z');
