name = "career-activity-tracker"
main = "src/index.js"
compatibility_date = "2024-09-23"

[assets]
directory = "./public"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "career_tracker_db"
database_id = "87af001e-d593-49c1-aa5f-a85bb73e55be"
